# theme = "catppuccin_macchiato"
theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = false
true-color = true
auto-completion = true
auto-format = true
scrolloff = 5
mouse = true
middle-click-paste = true
rulers = [80]
indent-heuristic = "simple"
soft-wrap.enable = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.search]
wrap-around = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

[editor.indent-guides]
render = true
character = "┆"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-type"]
separator = "│"

[keys.normal]
"C-s" = ":w"
"C-x" = ":wqa"
"C-q" = ":q"
"tab" = ":bn"
"S-l" = ":bp"
"C-o" = ":open ~/.config/helix/config.toml"
"C-l" = ":open ~/.config/helix/languages.toml"
"C-r" = ":config-reload"

[keys.insert]
"C-s" = ":w"
